# Generated by Django 3.2.9 on 2021-11-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('bank_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address_beneficiary', models.CharField(max_length=100)),
                ('phone_number_beneficiary', models.CharField(max_length=100)),
                ('bank_name_beneficiary', models.CharField(max_length=100)),
                ('full_name_2', models.CharField(max_length=100)),
                ('address_beneficiary_2', models.CharField(max_length=100)),
                ('phone_number_beneficiary_2', models.CharField(max_length=100)),
                ('bank_name_beneficiary_2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Beneficiary Detail',
                'verbose_name_plural': 'Beneficiary Details',
            },
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('other_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('means_of_identification', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'drivers license'), (2, 'international passport'), (3, 'voters card'), (4, 'others')], null=True)),
                ('identification_number', models.CharField(max_length=100)),
                ('PFA', models.CharField(max_length=100)),
                ('RSA', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('will_executors', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'meristem trustees'), (2, 'others')], null=True)),
                ('options', models.CharField(max_length=100)),
                ('bank_details', models.IntegerField()),
                ('beneficiary_details', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Client Detail',
                'verbose_name_plural': 'Client Details',
            },
        ),
    ]
