# Generated by Django 3.2.9 on 2021-11-11 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='bank_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.bankdetail'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='beneficiary_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.beneficiarydetail'),
        ),
    ]
