# Generated by Django 3.2.9 on 2021-11-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211111_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='beneficiary_details',
        ),
    ]
