# Generated by Django 3.2.9 on 2021-11-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_clientdetail_beneficiary_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='bank_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.bankdetail'),
        ),
    ]
