# Generated by Django 3.2.9 on 2021-11-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientdetail_bank_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='bank_details',
        ),
    ]
