# Generated by Django 3.2.9 on 2021-11-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_remove_clientdetail_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankdetail'),
        ),
    ]
