# Generated by Django 3.2.9 on 2021-11-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_clientdetail_bank_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetail',
            old_name='bank_details',
            new_name='bankdetail',
        ),
    ]
