# Generated by Django 3.2.9 on 2021-11-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_bank_details_clientdetail_bankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BankName',
                'verbose_name_plural': 'BankNames',
            },
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='beneficiary_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.beneficiarydetail'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='bankdetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankdetail'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankname'),
        ),
    ]
