# Generated by Django 3.2.9 on 2021-11-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20211120_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='bankdetail',
        ),
    ]
