# Generated by Django 3.2.9 on 2021-11-20 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_clientdetail_bankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='bankdetail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.bankdetail'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='beneficiary_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.beneficiarydetail'),
        ),
    ]
