# Generated by Django 3.2.9 on 2021-11-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20211120_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='email_2',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='values',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='values_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='means_of_identification',
            field=models.CharField(blank=True, choices=[('drivers license', 'drivers license'), ('international passport', 'international passport'), ('voters card', 'voters card'), ('others', 'others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='will_executors',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('meristem trustees', 'meristem trustees'), ('others', 'others')], null=True),
        ),
    ]
