# Generated by Django 3.2.9 on 2021-11-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20211121_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='will_executors',
            field=models.CharField(blank=True, choices=[('meristem trustees', 'meristem trustees'), ('others', 'others')], max_length=255, null=True),
        ),
    ]
