# Generated by Django 3.2.9 on 2021-11-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_clientdetail_will_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='bank_name_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bank', to='client.bankname'),
        ),
    ]
